# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Biquadrate' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  def testing_pods
    pod 'Quick'
    pod 'Nimble'
  end

  # Pods for Biquadrate

  target 'WorkingBiquadrateTests' do
    testing_pods
  end

end
